#################
### AUTOSTART ###
#################

exec-once = waybar & awww-daemon
exec-once = swaync
exec-once = hypridle
exec-once = protonvpn-app
exec-once = nextcloud
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store