###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = kitty -e yazi
$menu = rofi -show drun
$calc = rofi -show calc -modi calc -no-show-match -no-sort
$reload_waybar = ~/.config/hypr/reload.sh
$browser = helium-browser
$logout = wlogout
