source = ~/.config/hypr/modules/Monitors.conf
source = ~/.config/hypr/modules/Programs.conf
source = ~/.config/hypr/modules/Autostart.conf
source = ~/.config/hypr/modules/Env.conf
source = ~/.config/hypr/modules/Decorations.conf
source = ~/.config/hypr/modules/Animations.conf
source = ~/.config/hypr/modules/Input.conf
source = ~/.config/hypr/modules/Binds.conf
source = ~/.config/hypr/modules/Windows.conf