#  BACKGROUND (blurred)
background {
    monitor =
    path = ~/Pictures/wallpaper/*jpg
    blur_passes = 4
    blur_size = 10
    noise = 0.02
    contrast = 0.9
    brightness = 0.8
}

# GLASS PANEL
shape {
    monitor =
    size = 420, 360
    color = rgba(20, 20, 20, 0.45)

    rounding = 20
    border_size = 2
    # border_color = rgba(0, 255, 255, 0.6)
    border_color = rgba(139, 148, 158, 0.55)

    position = 0, 0
    halign = center
    valign = center
}

# BIG CLOCK
label {
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255,255,255,0.95)
    font_size = 80
    font_family = Fira Sans SemiBold

    position = 0, 90
    halign = center
    valign = center
}

# DATE
label {
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgba(200,200,200,0.7)
    font_size = 18
    font_family = Fira Sans SemiBold

    position = 0, 35
    halign = center
    valign = center
}

# USER
label {
    text = $USER
    color = rgba(255,255,255,0.85)
    font_size = 22
    font_family = Fira Sans SemiBold

    position = 0, -50
    halign = center
    valign = center
}

#  PASSWORD FIELD
input-field {
    size = 260, 50
    outline_thickness = 2

    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true

    # outer_color = rgba(0, 255, 255, 0.8)
    outer_color = rgba(139, 148, 158, 0.55)
    inner_color = rgba(15, 15, 15, 0.6)
    font_color = rgba(255,255,255,0.9)

    placeholder_text = Enter Password...
    fade_on_empty = false

    rounding = 12

    position = 0, -110
    halign = center
    valign = center
}
