background_opacity 0.85
background_blur 1

foreground #cdd6f4
background #0d0f12

selection_background #313244
selection_foreground #cdd6f4

cursor #6ee7ff

color0 #1e1e2e
color1 #f38ba8
color2 #a6e3a1
color3 #f9e2af
color4 #89b4fa
color5 #cba6f7
color6 #6ee7ff
color7 #bac2de

cursor_trail 3

scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

window_padding_width 12

font_size 15
